# 0 = disable
# 1 = warn
# 2 = error

files:
  ignore:
    - 'node_modules/**'
    - '../assets/scss/general/reset.scss'
rules:
  class-name-format:
    - 2
  final-newline:
    - 0
  hex-length:
    - 0
  property-sort-order:
    - 0
  no-color-literals:
    - 0
  indentation:
    - tab
  max-file-line-count:
    - 1000
  no-ids:
    - 1
  placeholder-in-extend:
    - 0
  no-extends:
    - 2
  space-before-brace:
    - 2
  empty-line-between-blocks:
    - 2
  space-after-colon:
    - 2
  one-declaration-per-line:
    - 2
  single-line-per-selector:
    - 2
  space-after-comma:
    - 2
  space-around-operator:
    - 2
  trailing-semicolon:
    - 2
  variable-name-format:
    - 2
